name: Build Test
on:
  push: null
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    needs: check-qemu
    uses: ./.github/workflows/tests.yaml
  check-qemu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Prepare QEMU
      uses: ./.github/workflows/actions/prepare-qemu
    - name: Verify QEMU
      run: qemu-system-arm --version
      shell: bash
    - name: Prepare Rust compiler toolchain
      uses: ./.github/workflows/actions/prepare-rust-toolchain
      if: '!cancelled()'
    - name: Verify Rust compiler toolchain registration
      run: cargo +segstk-rust --version
      shell: bash
      if: '!cancelled()'
    - name: Build Hopter and tests
      uses: ./.github/workflows/actions/build
