name: Build Test
on:
  push: null
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    needs: check-qemu
    uses: ./.github/workflows/tests.yaml
  check-qemu:
    runs-on: ubuntu-latest
    steps:
    - name: stepify-probe-check-qemu
      run: echo stepify-probe-check-qemu
    - name: stepify-fault-check-qemu
      run: exit 1
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Prepare QEMU
      uses: ./.github/workflows/actions/prepare-qemu
    - name: Verify QEMU
      run: qemu-system-arm --version
      shell: bash
    - name: stepify-tail-check-qemu
      run: echo stepify-tail-check-qemu
    - name: stepify-probe-check-rust-toolchain
      run: echo stepify-probe-check-rust-toolchain
      if: '!cancelled()'
      id: _m_check_rust_toolchain
    - name: Prepare Rust compiler toolchain
      uses: ./.github/workflows/actions/prepare-rust-toolchain
      if: '!cancelled() && steps._m_check_rust_toolchain.conclusion != ''failure'''
      id: _m_check_rust_toolchain_1
    - name: Verify Rust compiler toolchain registration
      run: cargo +segstk-rust --version
      shell: bash
      if: '!cancelled() && steps._m_check_rust_toolchain.conclusion != ''failure'' && steps._m_check_rust_toolchain_1.conclusion
        != ''failure'''
      id: _m_check_rust_toolchain_2
    - name: stepify-tail-check-rust-toolchain
      run: echo stepify-tail-check-rust-toolchain
      if: '!cancelled() && steps._m_check_rust_toolchain.conclusion != ''failure'' && steps._m_check_rust_toolchain_1.conclusion
        != ''failure'' && steps._m_check_rust_toolchain_2.conclusion != ''failure'''
    - name: stepify-probe-build
      run: echo stepify-probe-build
    - name: Build Hopter and tests
      uses: ./.github/workflows/actions/build
    - name: stepify-tail-build
      run: echo stepify-tail-build
